const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({ channel: 'chrome' });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(pathToFileURL(path.join(__dirname, 'index.html')).href);
    await page.screenshot({ path: path.join(__dirname, 'review-desktop.png'), fullPage: true });
    const desk = page.locator('#desk');
    await desk.getByRole('button', { name: 'View experience', exact: true }).click();
    await desk.getByRole('heading', { name: 'Experience', exact: true }).waitFor();
    await desk.getByRole('button', { name: 'Writing', exact: true }).click();
    await desk.getByRole('button', { name: /Read article/ }).click();
    await desk.getByRole('heading', { name: 'Why smaller wins' }).waitFor();
    await desk.getByRole('button', { name: '← Back to writing', exact: true }).click();
    await desk.getByRole('button', { name: 'Reset layout' }).click();
    assert.equal(await page.locator('#work .window').count(), 2);
    await desk.getByRole('button', { name: 'Focus', exact: true }).click();
    assert.equal(await page.locator('#work .window').count(), 1);
    await desk.getByRole('button', { name: 'Restore', exact: true }).click();
    assert.equal(await page.locator('#work .window').count(), 2);
    await desk.getByRole('button', { name: 'Appearance', exact: true }).click();
    await page.getByRole('button', { name: /Daylight — palette study/ }).click();
    assert.equal(await desk.getAttribute('data-look'), 'daylight');
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#looks').evaluate(el => el.open), false);
    await desk.getByRole('button', { name: 'Appearance', exact: true }).click();
    await page.locator('button[data-look="moonlit"]').click();
    await page.keyboard.press('Escape');
    await page.locator('#model').selectOption('website');
    assert.equal(await page.locator('.rail').isVisible(), false);
    await page.locator('#model').selectOption('desktop');
    await page.locator('#width').selectOption('phone');
    assert.equal(await page.locator('.rail').isVisible(), false);
    await page.locator('#width').selectOption('wide');
    await page.evaluate(() => { window.captured=[];window.lavish={queuePrompt:(message,options)=>window.captured.push({message,options:{data:options.data}})} });
    await page.locator('input[name="direction"]').first().check();
    assert.equal(await page.evaluate(() => window.captured.length), 0);
    await page.getByRole('button', { name: 'Queue direction for review' }).click();
    assert.equal(await page.evaluate(() => window.captured.length), 1);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.evaluate(() => scrollTo(0,0));
    await page.screenshot({ path: path.join(__dirname, 'review-mobile.png'), fullPage: true });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile overflow');
    await page.locator('#desk').screenshot({path:path.join(__dirname,'prototype-mobile.png')});
    await page.setViewportSize({width:1440,height:1050});
    await page.locator('#desk').screenshot({path:path.join(__dirname,'prototype-desktop.png')});
    assert.deepEqual(errors, []);
    console.log('PASS: navigation, reader/back, focus/restore/reset, appearance, modal Escape, two layouts, phone preview, feedback queue, mobile overflow, no browser errors.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode=1; });
