const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const {expect}=require('@playwright/test');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
(async()=>{const browser=await chromium.launch({channel:'chrome'});try{
const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const url=pathToFileURL(path.join(__dirname,'workspaces.html')).href;await page.goto(url);
const order=()=>page.locator('.tile').evaluateAll(es=>es.map(e=>e.dataset.tile));
await expect.poll(order).toEqual(['about','guide']);
await page.locator('[data-drag="about"]').dragTo(page.locator('[data-drag="guide"]'));
await expect.poll(order).toEqual(['guide','about']);
await page.locator('nav [data-ws="experience"]').click();
await expect(page.locator('#rail-label')).toHaveText('03 · Experience');
await page.getByRole('button',{name:'Move Experience / Career',exact:true}).click();
await expect.poll(order).toEqual(['work','career']);
await page.locator('nav [data-ws="welcome"]').click();await expect.poll(order).toEqual(['guide','about']);
await page.getByRole('button',{name:'Restore layout',exact:true}).click();await expect.poll(order).toEqual(['about','guide']);
await page.locator('nav [data-ws="experience"]').click();await expect.poll(order).toEqual(['work','career']);
await page.getByRole('button',{name:'Search anything',exact:true}).click();await page.locator('#query').fill('teams');await page.locator('#query').press('Enter');
await page.waitForURL('**#writing/small-teams');await expect(page.locator('#workspace-label')).toHaveText('02 · Writing');assert.equal(await page.locator('.tile.expanded').getAttribute('data-tile'),'reader');
await page.getByRole('button',{name:'Show all',exact:true}).click();assert.equal(await page.locator('.tile:visible').count(),2);
await page.getByRole('button',{name:'Restore layout',exact:true}).click();assert.equal(await page.locator('.reader').count(),1);
await page.getByRole('button',{name:'Search anything',exact:true}).click();await page.locator('#query').fill('zzzz');assert.match(await page.locator('#results').textContent(),/No matches/);await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Appearance',exact:true}).click();await page.getByRole('button',{name:/Daylight ·/}).click();assert.equal(await page.locator('body').getAttribute('data-look'),'daylight');await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Appearance',exact:true}).click();await page.getByRole('button',{name:/Moonlit ·/}).click();await page.keyboard.press('Escape');
await page.locator('nav [data-ws="welcome"]').click();await page.screenshot({path:path.join(__dirname,'workspaces-desktop.png'),fullPage:true});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(__dirname,'workspaces-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile overflow');
await page.goto(url+'#writing/small-teams');await page.getByRole('heading',{name:'Why smaller wins',exact:true}).waitFor();
assert.deepEqual(errors,[]);console.log('PASS: drag swap, Move control, per-workspace state, scoped restore, search + empty state, direct article route, focus/restore, appearance, mobile overflow, browser errors.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
